/* ============================================================
   All portfolio copy and structured data lives here.
   Edit text freely without touching core animation logic.
   ============================================================ */
const heroContent = {
  nav: [
    { label: "Home", href: "#top", active: true },
    { label: "About", href: "#about" },
    { label: "Projects", href: "#projects" },
    { label: "Experience", href: "#think" },
    { label: "Contact", href: "#contact" },
  ],

  cta: { label: "Let’s Talk", href: "#contact" },

  headline: "Anandhu",
  role: ["Software Developer", "Full-Stack · Systems Engineering"],
  meta: ["Laravel · PHP", "React · JavaScript", "MySQL · REST APIs", "Systems & DSA"],

  recruiterQuick: [
    { label: "GitHub", href: "https://github.com/Anandhu1028", external: true },
    { label: "Resume", href: "#contact", note: "Available upon request" },
    { label: "Stack", href: "#method" },
    { label: "Direct Email", href: "mailto:anandhusanthosh443@gmail.com" },
  ],

  notification: {
    name: "Anandhu",
    time: "now",
    lead: "Software Developer",
    message: "I’m Anandhu, a full-stack developer with 3+ years of experience building production-ready software, modern web applications, and automation solutions. I focus on scalable architecture, reliable engineering, and solving real-world business problems.",
  },

  section2: {
    sideLeft: ["Engineering", "Solutions."],
    sideRight: ["Reliability.", "Performance."],
  },

  /* ---- 02 · CORE ENGINEERING CAPABILITIES ---- */
  engineering: {
    eyebrow: "[ Engineering Capabilities ]",
    title: "Engineering Disciplines",
    subtitle: "Real software development grounded in systems thinking, algorithmic problem solving, and production reliability.",
    pillars: [
      {
        no: "01",
        name: "Software Development",
        summary: "Building production web applications, ERP/CRM platforms, APIs, and business systems.",
        tags: ["Laravel", "PHP", "React", "MySQL", "REST APIs"],
        description: "Full-lifecycle software engineering from database schema design through backend APIs and reactive interfaces. Specialized in building business management software, student tracking platforms, and custom operational tools that replace chaotic spreadsheets.",
      },
      {
        no: "02",
        name: "DSA & Problem Solving",
        summary: "Data structures, algorithms, complexity analysis, and structured problem solving.",
        tags: ["Time & Space", "Hash Maps", "Two Pointers", "Sliding Window", "Trees"],
        description: "Applying fundamental computer science principles to write optimal code. Analyzing time and space complexity tradeoffs ($O(1)$ through $O(n)$) to prevent performance regressions in data-heavy application workflows.",
      },
      {
        no: "03",
        name: "System Design",
        summary: "API design, database architecture, caching, queues, authentication, scalability, and reliability.",
        tags: ["Relational Schemas", "Transactions", "RBAC", "Queue Workers", "Data Integrity"],
        description: "Designing end-to-end application architectures with clean boundaries: normalized relational schemas (3NF), indexed foreign keys, database transactions (ACID), token-based authentication, and background queue workers.",
      },
      {
        no: "04",
        name: "System / Production Engineering",
        summary: "Deployment, debugging, monitoring, automation, performance, and maintaining production systems.",
        tags: ["Deployment", "Observability", "Structured Logging", "Automation", "Optimization"],
        description: "Software is not finished when it works locally. Keeping production systems reliable, observable, maintainable, and performant through automated database migrations, daily rotating log channels, and proactive query tuning.",
      },
    ],
    clientSolutions: {
      title: "Business & Client Capabilities",
      description: "Delivering working software tailored to solve concrete operational problems.",
      items: [
        {
          title: "Business Applications (ERP / CRM)",
          desc: "Custom CRM pipelines, admissions management, and business control centers with role-based permissions and central auditability.",
        },
        {
          title: "Modern Web Applications",
          desc: "Responsive, high-performance web applications built on Laravel and React with seamless REST API integration.",
        },
        {
          title: "API & Data Integrations",
          desc: "Structured RESTful APIs, third-party service connections, payment gateway integrations, and reliable data synchronization.",
        },
        {
          title: "Workflow Automation & Reporting",
          desc: "Scheduled background jobs, chunked Excel import/export processing, automated status notifications, and real-time operational reporting.",
        },
      ],
    },
  },

  /* ---- 03 · ABOUT ME (DO NOT ALTER CONTENT) ---- */
  about: {
    boxes: {
      who:   { title: "Who I Am",   sub: "Anandhu — full stack software developer." },
      what:  { title: "What I Do",  sub: "Web · App · Code" },
      think: { title: "My Projects", sub: "CRM · ERP · SaaS" },
    },
    views: {
      who: {
        eyebrow: "01 — Who I Am",
        head: "Anandhu A S",
        blocks: [
          { type: "paragraph", text: "I’m Anandhu, a full-stack developer with 3+ years of experience building production-ready software and modern web applications. I work on CRMs, ERPs, e-commerce platforms, custom business software, automation systems, and high-performance websites. I focus on clean architecture, scalable systems, reliable engineering, and creating practical solutions that solve real-world business problems." },
          { type: "paragraph", text: "My work starts with the business problem, not the code. Before I open an editor, I want to understand how leads move through your pipeline, where your team loses time, and what \"done\" actually looks like for the people using the system every day." },
          { type: "paragraph", text: "From there I design a data model and architecture that can grow with you — role-based access, clean APIs, and admin panels your staff can actually use — then build it in Laravel with the same care I'd want if it were my own business running on it." },
          { type: "heading", text: "Consultative, not just technical" },
          { type: "paragraph", text: "I ask about your workflow before recommending a build, so the system matches how your team actually works." },
          { type: "heading", text: "Architecture built to last" },
          { type: "paragraph", text: "Clean database design and modular Laravel code so adding new features later doesn't mean rebuilding from scratch." },
          { type: "heading", text: "Real-world business software" },
          { type: "paragraph", text: "CRMs, ERPs, and dashboards that handle the messy edge cases of actual operations, not just the demo path." },
        ],
      },
      what: {
        eyebrow: "02 — What I Do",
        head: "What I'm Offering",
        text: "Where code meets creative thinking — web, apps, systems, APIs, AI and automation. Built with passion, driven by creativity.",
      },
      think: {
        eyebrow: "03 — My Projects",
        head: "Selected Projects",
        text: "Business software built around real operational needs.",
      },
    },
  },

  /* ---- 04 · SELECTED WORKS & DEEP ENGINEERING CASE STUDIES ---- */
  works: {
    brand: "Anandhu Engineering",
    projects: [
      {
        key: "tims-lead",
        name: "TIMS Lead CRM",
        titlePrefix: "TIMS",
        titleAccent: "LEAD CRM",
        img: "assets/projects/tims-lead/1.png",
        gallery: [
          "assets/projects/tims-lead/2.png",
          "assets/projects/tims-lead/3.png",
          "assets/projects/tims-lead/4.png",
          "assets/projects/tims-lead/5.png",
          "assets/projects/tims-lead/6.png",
          "assets/projects/tims-lead/7.png",
          "assets/projects/tims-lead/8.png",
          "assets/projects/tims-lead/9.png",
          "assets/projects/tims-lead/10.png",
          "assets/projects/tims-lead/11.png",
          
        ],
        w: 1919,
        h: 945,
        cat: "CRM · SAAS",
        year: "2026",
        badge: "CRM · SAAS · 2026",
        accent: "#ff5a1f",
        isLive: true,
        liveUrl: "https://timslead.com",
        codeUrl: "https://github.com/Anandhu1028",
        title: "Lead lifecycle platform built for faster sales follow-up",
        summary: "A SaaS-based CRM to manage leads, track follow-ups, and improve sales team productivity.",
        stats: [
          { icon: "users", value: "500+", label: "Active Users" },
          { icon: "target", value: "85%", label: "Follow-up Rate" },
          { icon: "trend", value: "40%", label: "Conversion Increase" },
          { icon: "clock", value: "60%", label: "Time Saved" },
        ],
        problemTitle: "The Problem",
        problem: "Sales teams tracked leads across spreadsheets and WhatsApp, with no clear ownership, follow-up history, or conversion visibility. This led to slow responses, missed follow-ups, and lost deals.",
        keyChallenges: [
          "No centralized lead management",
          "Missed follow-ups and delayed responses",
          "Lack of visibility in conversion pipeline",
          "Manual tracking using spreadsheets & chats",
        ],
        businessImpact: [
          "Lost potential revenue",
          "Inefficient sales process",
          "High dependency on individuals",
          "Poor tracking and reporting",
        ],
        testimonial: {
          quote: "Tims Lead CRM helped us bring structure to our sales process. We now track every lead, every follow-up, and see real results.",
          author: "TIMS TEAM",
          role: "Product Team",
        },
        solutionTitle: "The Solution",
        solution: "Built a robust Laravel CRM covering the full lead lifecycle, with rule-based stage progression, automatic call recording, AI-generated call summaries, and automatic reassignment of stale leads.",
        solutionCapabilities: [
          "Centralized lead intake from multi-channel forms and API endpoints",
          "Automated lead assignment rules ensuring instant agent ownership",
          "Built-in activity timeline logging every touchpoint and call record",
          "Scheduled cron worker reallocating inactive leads after 15 days",
        ],
        solutionOutcomes: [
          "Unified pipeline visibility across all sales tiers and agents",
          "Zero dropped leads through strict SLA and automated reminders",
          "Instant context handoffs between SDRs and Account Executives",
          "Accurate conversion metrics for data-driven sales decisions",
        ],
        technologies: [
          { name: "Laravel", cat: "Backend Framework", role: "Modular architecture, Eloquent ORM, queued jobs" },
          { name: "PHP", cat: "Core Language", role: "Strictly typed services, repositories, and controllers" },
          { name: "MySQL", cat: "Relational Storage", role: "ACID transactions & indexed query schema" },
          { name: "Bootstrap 5", cat: "UI Interface", role: "Clean dashboard design & responsive layout" },
          { name: "JavaScript & AJAX", cat: "Client Layer", role: "Asynchronous table filtering & live status updates" },
          { name: "AI Call Summary", cat: "Intelligence", role: "Audio transcription & LLM call summary pipeline" },
          { name: "RBAC", cat: "Security", role: "Role-gated policies for Admin, Manager, and Agent" },
        ],
        engineering: [
          "Lead creation and assignment workflows giving every enquiry a clear owner and immutable audit log.",
          "Rule-based hot, warm, and cold stage progression enforcing consistent pipeline decisions.",
          "Full activity timeline with follow-up tracking and automatic call recording audio storage.",
          "AI-powered call summaries turning recorded customer conversations into structured next actions.",
          "Scheduled reassignment of stale leads after 15 days to eliminate pipeline bottlenecks.",
          "Role-based permissions (RBAC) and executive dashboards providing transparent operational visibility.",
        ],
        architecture: "Bootstrap 5 UI → AJAX / REST API → FormRequest Validation → Laravel Lead Services → MySQL Database (InnoDB ACID) → Background Queue / AI Summary Worker",
        result: "Centralized the sales workflow, reduced manual follow-up work, and gave managers real-time visibility into every executive's pipeline with an 85% follow-up adherence rate.",
      },
      {
        key: "point-mng",
        name: "Point Management System",
        titlePrefix: "POINT",
        titleAccent: "MANAGEMENT SYSTEM",
        img: "assets/projects/point-mng/1 (1).png",
        gallery: [
          "assets/projects/point-mng/1 (1).png",
          "assets/projects/point-mng/2.png",
          "assets/projects/point-mng/3.png",
          "assets/projects/point-mng/4.png",
          "assets/projects/point-mng/5.png",
          "assets/projects/point-mng/6.png",
          "assets/projects/point-mng/7.png",
          "assets/projects/point-mng/8.png",
          "assets/projects/point-mng/9.png",
        ],
        w: 1600,
        h: 900,
        cat: "BUSINESS SYSTEM · WEB APP",
        year: "2026",
        badge: "BUSINESS SYSTEM · WEB APP · 2026",
        accent: "#ff5a1f",
        isLive: true,
        liveUrl: "#",
        codeUrl: "https://github.com/Anandhu1028",
        title: "Centralized point operations with reliable balance tracking",
        summary: "A centralized point management platform for managing users, point transactions, approvals, balances, and administrative operations through a structured and auditable workflow.",
        stats: [
          { icon: "users", value: "Centralized", label: "Point Management" },
          { icon: "clock", value: "Real-time", label: "Balance Tracking" },
          { icon: "target", value: "Role-based", label: "Access Control" },
          { icon: "trend", value: "Auditable", label: "Transaction History" },
        ],
        problemTitle: "The Problem",
        problem: "Point operations were difficult to manage when user balances, point additions, deductions, and transaction records were handled across disconnected processes. Administrators needed a reliable way to control point allocation, maintain accurate balances, and track every transaction from a single system.",
        keyChallenges: [
          "Manual management of user point balances",
          "Difficult tracking of point additions and deductions",
          "Risk of inconsistent or incorrect point calculations",
          "Limited visibility into individual transaction history",
          "Time-consuming administrative operations",
          "Need for controlled access between administrators and users",
          "Difficulty maintaining a reliable audit trail",
        ],
        businessImpact: [
          "Increased administrative workload",
          "Higher risk of manual errors",
          "Slower point-related operations",
          "Poor visibility into account activity",
          "Difficult reconciliation of point transactions",
          "Reduced confidence in manually maintained records",
        ],
        testimonial: {
          quote: "A centralized system for managing point balances, transactions, and user activity with better control, consistency, and visibility.",
          author: "POINT MANAGEMENT SYSTEM",
          role: "Business Operations",
        },
        solutionTitle: "The Solution",
        solution: "Built a centralized Point Management System that manages the complete point lifecycle - from user management and point allocation to balance calculation, transaction tracking, and administrative reporting.",
        solutionCapabilities: [
          "Centralized user and account management",
          "Point credit and debit operations",
          "Automatic balance calculation",
          "Complete transaction history for each user",
          "Admin-controlled point adjustments",
          "Search, filtering, and transaction tracking",
          "Role-based access to system operations",
          "Structured dashboards for operational visibility",
        ],
        solutionOutcomes: [
          "Single source of truth for point balances",
          "Faster point management operations",
          "Reduced dependency on manual calculations",
          "Complete visibility into point transactions",
          "Easier investigation of account activity",
          "Better control over administrative actions",
        ],
        technologies: [
          { name: "Laravel / PHP", cat: "Backend", role: "Business logic, authentication, validation, workflows, and database operations" },
          { name: "MySQL", cat: "Database", role: "Users, point balances, transactions, roles, and system records" },
          { name: "Bootstrap / HTML / CSS / JavaScript", cat: "Frontend", role: "Responsive dashboards, tables, forms, and interactive controls" },
          { name: "JavaScript / AJAX", cat: "Client Layer", role: "Asynchronous point-management workflows and dynamic data updates" },
          { name: "Role-Based Access Control", cat: "Security", role: "Controlled access to administrative and user-level operations" },
          { name: "Database Transactions", cat: "Data Integrity", role: "Consistent updates to point balances and transaction records" },
        ],
        engineering: [
          "Centralized user and account workflows ensuring every point operation is associated with a specific user and transaction.",
          "Structured credit and debit logic maintaining consistent point balances across account operations.",
          "Transaction-based updates preventing partial point changes and maintaining database consistency.",
          "Validation and authorization layers controlling who can perform sensitive point-management operations.",
          "Search, filtering, and transaction-history workflows allowing administrators to quickly investigate account activity.",
          "Administrative reporting and dashboard views providing operational visibility into users, balances, and point activity.",
        ],
        architecture: "Bootstrap UI → HTTP Request → Validation → Authorization → Point Management Logic → MySQL Database → Updated Balance + Transaction History",
        result: "Centralized point operations into a structured system, giving administrators better control over user balances, point transactions, and account activity while reducing reliance on manual tracking.",
      },
      {
        key: "construction",
        name: "Construction Management System",
        titlePrefix: "CONSTRUCTION",
        titleAccent: "MANAGEMENT SYSTEM",
        img: "assets/projects/construction/1.png",
        gallery: [
          "assets/projects/construction/1.png",
          "assets/projects/construction/2.png",
          "assets/projects/construction/3.png",
          "assets/projects/construction/4.png",
          "assets/projects/construction/5.png",
          "assets/projects/construction/6.png",
          "assets/projects/construction/7.png",
          "assets/projects/construction/8.png",
          "assets/projects/construction/9.png",
          "assets/projects/construction/10.png",
          "assets/projects/construction/11.png",
        ],
        w: 1600,
        h: 900,
        cat: "CONSTRUCTION ERP · PROJECT MANAGEMENT",
        year: "2026",
        badge: "CONSTRUCTION ERP · PROJECT MANAGEMENT · 2026",
        accent: "#ff5a1f",
        isLive: true,
        liveUrl: "#",
        codeUrl: "https://github.com/Anandhu1028",
        title: "Enterprise construction operations in one centralized platform",
        summary: "An enterprise Construction ERP for managing projects, stages, site attendance, expenses, payments, profitability, and client visibility through a centralized platform.",
        stats: [
          { icon: "trend", value: "End-to-End", label: "Project Lifecycle" },
          { icon: "target", value: "GPS Verified", label: "Site Attendance" },
          { icon: "clock", value: "Real-Time", label: "Financial Tracking" },
          { icon: "users", value: "Client Ready", label: "Project Portal" },
        ],
        problemTitle: "The Problem",
        problem: "Construction operations were managed across spreadsheets, phone calls, messaging apps, and manually prepared reports. This made it difficult to maintain accurate project progress, monitor site activity, control expenses, and give clients timely visibility into project status.",
        keyChallenges: [
          "Project progress scattered across multiple tools and communication channels",
          "Difficult tracking of project stages and completion status",
          "No reliable verification of supervisor/site attendance",
          "Manual recording and reconciliation of project expenses",
          "Limited visibility into project budgets and profitability",
          "Difficult coordination between office teams and site supervisors",
          "Clients lacked real-time visibility into project progress",
          "Manual preparation of project and financial reports",
        ],
        businessImpact: [
          "Higher administrative overhead",
          "Delayed project status reporting",
          "Increased risk of inaccurate expense records",
          "Limited accountability for site operations",
          "Difficult budget and profitability monitoring",
          "Increased communication gaps between teams and clients",
        ],
        testimonial: {
          quote: "A centralized construction operations platform connecting project progress, site activity, financial control, and client visibility.",
          author: "CONSTRUCTION MANAGEMENT SYSTEM",
          role: "Project Operations",
        },
        solutionTitle: "The Solution",
        solution: "Built a centralized Construction ERP covering the complete project lifecycle - from project and stage planning to GPS-verified site attendance, expense management, payment tracking, financial reporting, and client communication.",
        solutionCapabilities: [
          "Centralized project and stage management",
          "GPS-based supervisor check-in and attendance verification",
          "Project expense and budget management",
          "Stage-based payment tracking",
          "Client portal with project status visibility",
          "Project progress and site monitoring",
          "Profit and loss reporting",
          "Automated operational alerts and notifications",
        ],
        solutionOutcomes: [
          "Centralized visibility across active construction projects",
          "Improved accountability for site supervisors",
          "Better control over project expenses and budgets",
          "Faster access to project financial information",
          "Transparent stage and payment tracking",
          "Improved communication between project teams and clients",
        ],
        technologies: [
          { name: "Laravel", cat: "Backend Framework", role: "Modular application architecture, business workflows, authentication, validation, and project services" },
          { name: "PHP", cat: "Core Language", role: "Server-side application logic and domain-level operations" },
          { name: "MySQL", cat: "Database", role: "Projects, stages, attendance, expenses, payments, users, and financial records" },
          { name: "Bootstrap 5", cat: "UI Interface", role: "Responsive dashboards, administrative interfaces, forms, and project management views" },
          { name: "JavaScript + AJAX", cat: "Client Layer", role: "Asynchronous data operations, dynamic filtering, dashboard updates, and interactive workflows" },
          { name: "GPS Verification", cat: "Location", role: "Location-based validation for supervisor attendance and site check-ins" },
          { name: "Financial Dashboard", cat: "Finance", role: "Budget, expenses, payments, profitability, and project-level financial visibility" },
        ],
        engineering: [
          "Project and stage workflows providing structured lifecycle management from project initiation through completion.",
          "GPS-verified supervisor check-ins associating attendance records with the designated construction site.",
          "Expense recording and budget tracking providing project-level financial visibility and controlled expenditure monitoring.",
          "Stage-based payment workflows connecting project milestones with payment progress and financial records.",
          "Client-facing project portal exposing relevant progress information without exposing internal administrative operations.",
          "Automated notifications and alerts surfacing important project, payment, attendance, and operational events.",
        ],
        architecture: "Bootstrap UI → AJAX / REST Requests → Authentication & RBAC → Request Validation → Construction Domain Services → Projects & Stages → Finance & Payments → Attendance + GPS Data → MySQL Database → Dashboards / Reports / Portal → Alerts & Notifications",
        result: "Centralized construction operations into a single platform, providing management with better control over project progress, site activity, expenses, payments, and profitability while giving clients transparent access to project updates.",
      },
      {
        key: "student-portal-crm",
        name: "TIMS Admission, Student Lifecycle & Finance ERP",
        titlePrefix: "TIMS",
        titleAccent: "STUDENT LIFECYCLE ERP",
        img: "assets/projects/student-portal-crm/1.png",
        gallery: [
          "assets/projects/student-portal-crm/1.png",
          "assets/projects/student-portal-crm/2.png",
          "assets/projects/student-portal-crm/3.png",
          "assets/projects/student-portal-crm/4.png",
          "assets/projects/student-portal-crm/5.png",
          "assets/projects/student-portal-crm/6.png",
          "assets/projects/student-portal-crm/7.png",
          "assets/projects/student-portal-crm/8.png",
          "assets/projects/student-portal-crm/9.png",
          "assets/projects/student-portal-crm/10.png",
          "assets/projects/student-portal-crm/11.png",
          "assets/projects/student-portal-crm/12.png",
          "assets/projects/student-portal-crm/13.png",
          "assets/projects/student-portal-crm/14.png",
          "assets/projects/student-portal-crm/15.png",
          "assets/projects/student-portal-crm/16.png",
          "assets/projects/student-portal-crm/17.png",
          "assets/projects/student-portal-crm/18.png",
          "assets/projects/student-portal-crm/19.png",
          "assets/projects/student-portal-crm/20.png",
          "assets/projects/student-portal-crm/21.png",
        ],
        w: 1600,
        h: 900,
        cat: "ERP · EDUCATION · ADMISSIONS · FINANCE",
        year: "2026",
        badge: "ERP · EDUCATION · ADMISSIONS · FINANCE · 2026",
        accent: "#ff5a1f",
        isLive: true,
        liveUrl: "https://timslead.com",
        codeUrl: "https://github.com/Anandhu1028",
        title: "Admission, student lifecycle, and finance operations in one controlled ERP",
        summary: "An enterprise education management platform for handling student admissions, course enrollment, document verification, payments, approvals, batch management, collections, and the complete student lifecycle through role-based workflows.",
        stats: [
          { icon: "target", value: "Admission Workflow", label: "RPL & Degree Enrollment" },
          { icon: "trend", value: "Finance Control", label: "Payments, Discounts & Balances" },
          { icon: "users", value: "Document Verification", label: "Upload, Review & Exceptions" },
          { icon: "clock", value: "Lifecycle Management", label: "Track ID, Batches & Status" },
        ],
        problemTitle: "The Problem",
        problem: "Student admissions involved multiple teams, manual verification, payment follow-ups, and disconnected administrative processes. Admissions, accounts, document verification, course fees, and student records needed to operate through a single controlled workflow while preserving financial and operational accuracy.",
        keyChallenges: [
          "Different admission workflows for RPL and Degree students",
          "Course and fee structures dependent on university and program",
          "Manual collection of personal and educational information",
          "Required-document tracking and verification",
          "Handling cases where documents are temporarily unavailable",
          "Payment approval requiring Accounts-team verification",
          "Managing discounts, promo codes, and payment balances",
          "Tracking pending, approved, and rejected admissions",
          "Maintaining consistent student and payment records",
          "Managing batches and student status throughout the lifecycle",
          "Handling temporary and drop-case students",
          "Generating reports and collection summaries across operations",
        ],
        businessImpact: [
          "Increased administrative workload",
          "Delayed admission processing",
          "Difficulty tracking pending payments",
          "Higher risk of inconsistent student records",
          "Limited visibility into collections and outstanding balances",
          "Manual coordination between BDE, Branch, Accounts, and administration teams",
        ],
        testimonial: {
          quote: "A controlled student lifecycle platform connecting admissions, verification, payments, activation, batch management, and collection visibility.",
          author: "TIMS PORTAL",
          role: "Education Operations",
        },
        solutionTitle: "The Solution",
        solution: "Built a centralized TIMS Portal that manages the admission lifecycle from student registration and document collection through payment approval, Track ID generation, enrollment, batch allocation, invoicing, and ongoing student management.",
        solutionCapabilities: [
          "RPL and Degree-based admission workflows",
          "Personal and educational information management",
          "University, course, and fee configuration",
          "Required-document upload and verification",
          "Document exception handling for unavailable documents",
          "Payment creation with configurable payment types",
          "Discounts and promo-code management",
          "BDE and branch assignment",
          "Automatic next-payment date calculation",
          "Accounts-controlled payment approval workflow",
          "Payment rejection with remarks",
          "Approval-based Track ID generation",
          "Automated welcome email after qualifying payment approval",
          "Automatic invoice generation for active payments",
          "Student payment profile with balance and payment history",
          "Batch-wise student management",
          "Temporary-list and drop-case management",
          "Collection and outstanding-balance tracking",
        ],
        solutionOutcomes: [
          "Controlled admissions through structured RPL and Degree workflows",
          "Clear student-level payment and outstanding-balance visibility",
          "Accounts-controlled payment approval and rejection handling",
          "Automated Track ID generation and student activation",
          "Document compliance and exception tracking",
          "Batch management across the student lifecycle",
          "Centralized collection, invoice, and upcoming-payment monitoring",
          "Operational reporting across admissions, students, payments, and batches",
        ],
        technologies: [
          { name: "Laravel", cat: "Framework", role: "Admission workflows, business logic, authentication, validation, and administrative operations" },
          { name: "PHP", cat: "Backend", role: "Server-side application and domain logic" },
          { name: "MySQL", cat: "Database", role: "Students, courses, universities, payments, documents, batches, users, and operational records" },
          { name: "Bootstrap 5", cat: "UI Interface", role: "Responsive administrative interface and management dashboards" },
          { name: "AJAX / JavaScript", cat: "Client Layer", role: "Dynamic forms, dependent selections, filtering, and asynchronous operations" },
          { name: "RBAC", cat: "Security", role: "Role-based permissions across BDE, Branch, Accounts, Administration, and operational users" },
        ],
        engineering: [
          "Dynamic admission workflows adapt to the selected education pathway, supporting separate RPL and Degree enrollment requirements.",
          "University and course-based fee logic determines availability and applicable amounts through configured program and fee structures.",
          "Payment approval keeps submissions pending until Accounts verification, while rejected payments retain remarks and stay excluded from balances.",
          "Approval-based Track ID generation issues identifiers only after the required admission and payment workflow is complete.",
          "Document verification states support required uploads, review, and controlled handling for missing or temporarily unavailable documents.",
          "Approved payments trigger downstream communication and invoice generation, with subsequent payments generating their corresponding invoices.",
          "Each student maintains a consolidated financial profile containing payment history, approved amounts, balances, discounts, and upcoming payments.",
          "Lifecycle and batch management supports active, temporary, and drop-case states according to defined operational rules.",
        ],
        architecture: "Admission Entry → RPL / Degree Selection → Personal + Education Details → University + Course Selection → Fee Calculation → Discount / Promo Code → BDE + Branch Assignment → Document Upload → Payment Entry → Student PENDING → Accounts Approval → Track ID + Invoice → Batch Assignment → Payment Tracking → Student Lifecycle",
        result: "Centralized the student admission and financial lifecycle into a single controlled platform, connecting admissions, document verification, payments, Accounts approval, student activation, batch management, and reporting.",
      },
      {
        key: "yellow-care",
        name: "Yellow Care - Medical Equipment Rental & E-Commerce Platform",
        titlePrefix: "YELLOW CARE",
        titleAccent: "MEDICAL E-COMMERCE",
        img: "assets/projects/medi.-equip/2 (1).png",
        gallery: [
          "assets/projects/medi.-equip/2 (1).png",
          "assets/projects/medi.-equip/2 (8).png",
          "assets/projects/medi.-equip/3.png",
          "assets/projects/medi.-equip/4.png",
          "assets/projects/medi.-equip/5.png",
          "assets/projects/medi.-equip/6.png",
          "assets/projects/medi.-equip/7.png",
          "assets/projects/medi.-equip/8.png",
        ],
        w: 1600,
        h: 900,
        cat: "MEDICAL E-COMMERCE · RENTAL & SALES",
        year: "2026",
        badge: "MEDICAL E-COMMERCE · RENTAL & SALES · 2026",
        accent: "#f2c94c",
        isLive: true,
        liveUrl: "#",
        codeUrl: "https://github.com/Anandhu1028",
        title: "Medical equipment rental and sales with transparent booking",
        summary: "A medical equipment e-commerce platform enabling customers to discover, compare, rent, and purchase healthcare equipment with transparent pricing, doorstep delivery, and dedicated support.",
        stats: [
          { icon: "trend", value: "Rental & Sales", label: "Flexible Equipment Options" },
          { icon: "users", value: "Product Catalog", label: "Medical Equipment Discovery" },
          { icon: "target", value: "Online Booking", label: "Equipment Rental Workflow" },
          { icon: "clock", value: "Doorstep Delivery", label: "Delivery & Support" },
        ],
        problemTitle: "The Problem",
        problem: "Customers looking for medical equipment often had difficulty finding the right equipment, understanding rental pricing, checking availability, and arranging delivery through traditional offline channels. The business needed a digital storefront that could simplify the journey from product discovery to equipment selection, rental calculation, booking, and delivery.",
        keyChallenges: [
          "Medical equipment distributed across different product categories",
          "Customers needed clear product information before booking",
          "Rental pricing depended on selected duration",
          "Manual handling of equipment enquiries and bookings",
          "Limited visibility into available rental options",
          "Customers needed convenient contact and booking channels",
          "Product discovery needed to work across multiple equipment categories",
          "Customers required delivery, support, and rental information before purchase",
        ],
        businessImpact: [
          "Higher dependency on phone and WhatsApp enquiries",
          "Slower equipment discovery",
          "Manual rental-price communication",
          "Increased effort in handling customer enquiries",
          "Limited digital visibility for the equipment catalog",
          "Fragmented customer journey from discovery to booking",
        ],
        testimonial: {
          quote: "A clearer digital path from finding the right medical equipment to understanding rental options and starting a booking.",
          author: "YELLOW CARE",
          role: "Medical Equipment Commerce",
        },
        solutionTitle: "The Solution",
        solution: "Built a responsive medical equipment commerce platform that combines product discovery, category-based browsing, rental pricing, equipment details, booking workflows, and customer support into a single digital experience.",
        solutionCapabilities: [
          "Medical equipment catalog",
          "Category-based product navigation",
          "Product search",
          "Individual equipment detail pages",
          "Rental duration selection",
          "Dynamic rental-price calculation",
          "Transportation fee calculation",
          "Online booking workflow",
          "WhatsApp-based enquiry and order option",
          "Product sharing",
          "Similar-product recommendations",
          "Delivery and support information",
          "FAQ section",
          "Responsive mobile and desktop experience",
        ],
        solutionOutcomes: [
          "Digital catalog for browsing medical equipment without manual enquiries",
          "Transparent rental pricing based on selected duration",
          "Simplified booking connected directly to the product experience",
          "Improved discovery through search, categories, and recommendations",
          "Clear conversion paths through booking, WhatsApp, and contact actions",
          "Greater customer confidence through delivery, support, terms, and FAQ content",
        ],
        technologies: [
          { name: "HTML / CSS / Bootstrap", cat: "Frontend", role: "Responsive storefront, product catalog, navigation, cards, and booking interfaces" },
          { name: "JavaScript / AJAX", cat: "Client Layer", role: "Dynamic product interactions, rental-duration selection, pricing updates, and UI components" },
          { name: "PHP / Laravel", cat: "Backend", role: "Product management, booking workflows, customer requests, pricing logic, and business operations" },
          { name: "MySQL", cat: "Database", role: "Product catalog, categories, rental pricing, customer information, and booking records" },
          { name: "WhatsApp Integration", cat: "Communication", role: "Direct customer enquiry and booking communication" },
          { name: "Mobile + Desktop", cat: "Responsive Design", role: "Shopping experience optimized across desktop, tablet, and mobile devices" },
        ],
        engineering: [
          "Structured medical equipment into searchable categories covering monitors, CPAP/BiPAP devices, oxygen equipment, wheelchairs, and hospital-care products.",
          "Rental pricing is calculated from the selected equipment and duration, with applicable transportation charges included in the final amount.",
          "Dedicated product pages combine equipment descriptions, service benefits, rental information, terms, pricing, and booking actions.",
          "Customers can select a rental duration, review the calculated total, and initiate booking without manual price calculation.",
          "Search, categories, product cards, and similar-product recommendations create multiple paths to discover relevant equipment.",
          "Booking, WhatsApp ordering, contact actions, and product sharing provide direct conversion paths from discovery to enquiry.",
          "FAQ, delivery, sanitization, support, and rental-term content address customer concerns before booking.",
        ],
        architecture: "Homepage / Search → Product Categories → Equipment Catalog → Product Details → Select Duration → Rental Price + Transportation Fee → Total Amount → Book Equipment → WhatsApp / Contact → Delivery & Support",
        result: "Transformed the medical equipment business into a structured digital storefront, making it easier for customers to discover equipment, understand rental options, calculate pricing, and initiate bookings or enquiries online.",
      },
      {
        key: "ecom",
        name: "Modern E-Commerce Platform",
        titlePrefix: "MODERN",
        titleAccent: "E-COMMERCE PLATFORM",
        img: "assets/projects/ecom/1.png",
        gallery: [
          "assets/projects/ecom/1.png",
          "assets/projects/ecom/2.png",
          "assets/projects/ecom/3.png",
          "assets/projects/ecom/4.png",
          "assets/projects/ecom/5.png",
          "assets/projects/ecom/6.png",
          "assets/projects/ecom/7.png",
          "assets/projects/ecom/8.png",
        ],
        w: 1600,
        h: 900,
        cat: "E-COMMERCE · WEB PLATFORM",
        year: "2026",
        badge: "E-COMMERCE · WEB PLATFORM · 2026",
        accent: "#e8b54a",
        isLive: true,
        liveUrl: "#",
        codeUrl: "https://github.com/Anandhu1028",
        title: "Modern shopping experience from discovery to delivery",
        summary: "A modern, conversion-focused e-commerce platform designed for seamless product discovery, personalized shopping, secure checkout, and end-to-end order management across desktop and mobile.",
        stats: [
          { icon: "users", value: "Product Catalog", label: "Discovery & Collections" },
          { icon: "target", value: "Personalized", label: "Shopping Experience" },
          { icon: "trend", value: "Secure Checkout", label: "Payment Workflow" },
          { icon: "clock", value: "End-to-End", label: "Order Management" },
        ],
        problemTitle: "The Problem",
        problem: "Traditional online stores often create friction through cluttered navigation, poor product discovery, limited personalization, and complicated checkout experiences. The platform needed a modern shopping experience that could handle the complete customer journey while remaining fast, responsive, and easy to manage.",
        keyChallenges: [
          "Large product catalogs difficult to browse efficiently",
          "Limited search and filtering capabilities",
          "Inconsistent product discovery across devices",
          "Complex cart and checkout workflows",
          "Lack of personalized shopping experiences",
          "Difficult management of inventory and product variants",
          "Limited visibility into customer orders and purchasing activity",
          "Need for a responsive experience across desktop, tablet, and mobile",
        ],
        businessImpact: [
          "Higher friction during product discovery",
          "Increased checkout abandonment risk",
          "Poor mobile shopping experience",
          "More manual order-management operations",
          "Limited visibility into customer and product performance",
        ],
        testimonial: {
          quote: "A streamlined commerce experience connecting product discovery, checkout, inventory, and order visibility across devices.",
          author: "MODERN E-COMMERCE PLATFORM",
          role: "Commerce Operations",
        },
        solutionTitle: "The Solution",
        solution: "Built a modern e-commerce platform connecting product discovery, catalog management, cart, checkout, payments, customer accounts, and order tracking into a unified shopping experience.",
        solutionCapabilities: [
          "Modern product catalog and collection pages",
          "Advanced product search",
          "Category and attribute-based filtering",
          "Product variants such as size, color, and configuration",
          "Wishlist and favorites",
          "Dynamic shopping cart",
          "Coupon and promotional-code support",
          "Secure checkout workflow",
          "Multiple payment methods",
          "Customer account and order history",
          "Real-time order-status tracking",
          "Product recommendations",
          "Inventory management",
          "Admin product and order management",
          "Sales and customer analytics",
        ],
        solutionOutcomes: [
          "Better product discovery through search, categories, filters, collections, and recommendations",
          "Frictionless product-to-cart-to-checkout journey",
          "Flexible commerce support for variants, promotions, coupons, and payments",
          "Centralized product, inventory, customer, order, and promotion management",
          "Order-history and status visibility for customers after purchase",
          "Consistent shopping experience across desktop, tablet, and mobile",
        ],
        technologies: [
          { name: "Responsive Web UI", cat: "Frontend", role: "Reusable storefront components, product pages, catalog views, and mobile shopping experiences" },
          { name: "Commerce Workflows", cat: "Application", role: "Catalog, variants, wishlist, cart, checkout, customer accounts, and order lifecycle" },
          { name: "Product & Order Data", cat: "Data Layer", role: "Structured products, customers, orders, payments, inventory, and promotions" },
          { name: "Search & Filtering", cat: "Discovery", role: "Catalog search, category browsing, attributes, availability, and recommendations" },
          { name: "Payment Integration", cat: "Transactions", role: "Checkout payment handling and order confirmation workflow" },
          { name: "Responsive Design", cat: "Experience", role: "Consistent interaction across desktop, tablet, and mobile devices" },
        ],
        engineering: [
          "Structured product data supports categories, collections, variants, attributes, pricing, inventory, and product media.",
          "Search and discovery workflows combine category, price, attribute, and availability filters to reduce browsing friction.",
          "Persistent cart workflows maintain selections, quantities, variants, pricing, discounts, and calculated totals.",
          "Checkout is structured across customer information, delivery, pricing validation, payment, and order confirmation stages.",
          "Order state management covers pending, confirmed, processing, shipped, delivered, cancelled, and returned states.",
          "Product availability is connected with order operations to reduce the risk of selling unavailable inventory.",
          "Configurable coupons, promotional codes, discounts, and eligibility rules support flexible commerce campaigns.",
          "Reusable responsive components provide a consistent shopping experience across desktop and mobile devices.",
        ],
        architecture: "Web / Mobile UI → Product Discovery → Catalog / Search → Product Service → Cart Management → Pricing Engine → Discounts + Inventory → Checkout → Payment Gateway → Order Service → Inventory + Customer + Notifications → Order Tracking → Fulfillment → Delivery",
        result: "Delivered a modern commerce experience that simplifies product discovery, reduces checkout friction, and connects customers with a complete purchasing journey from browsing to order tracking.",
      },
      {
        key: "restaurant",
        name: "Restaurant POS & Order Management System",
        titlePrefix: "RESTAURANT POS",
        titleAccent: "ORDER MANAGEMENT",
        img: "assets/projects/restaurant/Screenshot 2026-09-08 110254.png",
        gallery: [
          "assets/projects/restaurant/Screenshot 2026-09-08 110254.png",
        ],
        w: 1600,
        h: 900,
        cat: "RESTAURANT TECH · POS · ORDER MANAGEMENT",
        year: "2026",
        badge: "RESTAURANT TECH · POS · ORDER MANAGEMENT · 2026",
        accent: "#e8b54a",
        isLive: true,
        liveUrl: "#",
        codeUrl: "https://github.com/Anandhu1028",
        title: "Restaurant operations managed through one centralized POS",
        summary: "A modern restaurant management platform for managing menus, dine-in orders, tables, sales, inventory, customers, and daily operations through a centralized POS interface.",
        stats: [
          { icon: "target", value: "Fast POS", label: "Order Entry" },
          { icon: "users", value: "Table-Based", label: "Dine-in Ordering" },
          { icon: "trend", value: "Reporting", label: "Sales & Revenue" },
          { icon: "clock", value: "Centralized", label: "Daily Operations" },
        ],
        problemTitle: "The Problem",
        problem: "Restaurants often rely on disconnected tools and manual processes to manage orders, tables, menus, inventory, and daily sales. This creates operational friction during busy service periods and makes it difficult for managers to maintain accurate financial and inventory visibility.",
        keyChallenges: [
          "Manual order taking and processing",
          "Slow access to menu items during service",
          "Difficult table and floor management",
          "Limited visibility into active orders",
          "Manual sales and revenue reporting",
          "Inventory tracking disconnected from daily operations",
          "Difficult management of cash transactions and shifts",
          "Customer information maintained separately",
          "Limited operational visibility for restaurant managers",
        ],
        businessImpact: [
          "Slower order processing",
          "Increased risk of order-entry errors",
          "Longer customer wait times",
          "Difficult reconciliation of daily sales",
          "Higher inventory-management overhead",
          "Limited visibility into restaurant performance",
        ],
        testimonial: {
          quote: "A centralized restaurant operations platform connecting menu, table, order, payment, inventory, cash, and customer workflows.",
          author: "RESTAURANT POS",
          role: "Daily Operations",
        },
        solutionTitle: "The Solution",
        solution: "Built a centralized restaurant POS and operations platform connecting menu management, table planning, order processing, sales reporting, inventory, cash management, and customer records in a single workflow.",
        solutionCapabilities: [
          "Digital restaurant menu",
          "Category-based menu organization",
          "Fast item search",
          "Add-ons and item customization",
          "Quantity and cart management",
          "Dine-in order management",
          "Table and floor planning",
          "Active order tracking",
          "Sales and revenue reports",
          "Menu management",
          "Inventory reports",
          "Shift and cash management",
          "Customer directory",
          "Store settings",
          "Order and payment summaries",
        ],
        solutionOutcomes: [
          "Faster order creation and modification directly from the menu interface",
          "Table and floor information connected with active dine-in orders",
          "Centralized menu categories, pricing, and availability management",
          "Structured sales and revenue reporting instead of manual calculations",
          "Shift and cash-log support for daily financial reconciliation",
          "Inventory reporting connected to restaurant operations",
          "Centralized customer records for service and operational use",
        ],
        technologies: [
          { name: "Laravel / PHP", cat: "Backend", role: "Application logic, authentication, order workflows, menu management, and business rules" },
          { name: "MySQL", cat: "Database", role: "Menu items, categories, orders, tables, customers, payments, and inventory" },
          { name: "Bootstrap 5", cat: "UI Interface", role: "Responsive POS interface and management screens" },
          { name: "JavaScript / AJAX", cat: "Client Layer", role: "Dynamic menu interactions, cart updates, order operations, and UI actions" },
          { name: "DataTables", cat: "Operations", role: "Searchable, filterable, and paginated operational data" },
          { name: "Chart.js", cat: "Analytics", role: "Sales, revenue, and restaurant performance analytics" },
        ],
        engineering: [
          "Fast order-entry interface lets staff browse menu categories, select items, configure add-ons, adjust quantities, and build orders without leaving the POS screen.",
          "Order totals are calculated from item quantities, add-ons, taxes, discounts, and applicable charges before an order is placed.",
          "Orders are associated with specific table locations to support dine-in operations and restaurant floor management.",
          "Menu items are organized into categories with configurable pricing and availability for efficient restaurant operations.",
          "Transaction data is structured for sales reporting, revenue analysis, and operational performance monitoring.",
          "Inventory reporting provides management with visibility into stock-related operations and consumption.",
          "Shift and cash-log functionality supports daily reconciliation and operational accountability.",
          "Customer records provide a centralized view of customer information and restaurant interactions.",
        ],
        architecture: "POS Staff → Table Selection → Menu Catalog → Category / Item Search → Item + Add-ons → Cart Management → Pricing / Tax / Discount → Order Record → Kitchen Workflow + Payment Record + Table Status → Sales Database → Reports / Inventory / Customer Records",
        result: "Centralized restaurant operations into a single POS platform, giving staff a faster way to manage orders while giving management better visibility into sales, tables, inventory, cash operations, and customer activity.",
      },
      {
        key: "travel-agency",
        name: "Travela Agency",
        titlePrefix: "TRAVELA",
        titleAccent: "AGENCY",
        img: "assets/projects/travel-agency/1 (1).png",
        gallery: [
          "assets/projects/travel-agency/1 (1).png",
          "assets/projects/travel-agency/2.png",
          "assets/projects/travel-agency/3.png",
          "assets/projects/travel-agency/4.png",
          "assets/projects/travel-agency/5.png",
          "assets/projects/travel-agency/6.png",
        ],
        w: 1600,
        h: 900,
        cat: "TRAVEL · TOURISM · CORPORATE WEBSITE",
        year: "2026",
        badge: "TRAVEL · TOURISM · CORPORATE WEBSITE · 2026",
        accent: "#e8b54a",
        isLive: true,
        liveUrl: "#",
        codeUrl: "https://github.com/Anandhu1028",
        title: "A visually engaging travel website built for discovery and enquiries",
        summary: "A modern travel agency website showcasing destinations, tour packages, travel experiences, and services through an immersive, responsive, and enquiry-focused digital experience.",
        stats: [
          { icon: "target", value: "Destination Showcase", label: "Travel Discovery" },
          { icon: "trend", value: "Tour Packages", label: "Clear Presentation" },
          { icon: "users", value: "Travel Gallery", label: "Visual Storytelling" },
          { icon: "clock", value: "Enquiry Focused", label: "Contact Conversion" },
        ],
        problemTitle: "The Challenge",
        problem: "Travellers need to quickly understand where they can travel, what experiences are available, and why they should choose the agency. The website needed to present destinations and packages attractively while making it easy for visitors to contact the agency.",
        keyChallenges: [
          "Presenting multiple destinations in an engaging way",
          "Showcasing tour packages without overwhelming visitors",
          "Communicating package highlights and travel experiences clearly",
          "Building trust through agency information and customer-focused content",
          "Making enquiry and contact actions easy to find",
          "Creating a responsive experience across desktop and mobile",
        ],
        businessImpact: [
          "Destination information easier to explore",
          "Clearer presentation of tour packages",
          "Stronger travel-focused visual identity",
          "More accessible enquiry and contact pathways",
          "Consistent experience across desktop and mobile",
        ],
        testimonial: {
          quote: "A destination-led digital experience that helps travellers explore the agency's offerings and take the next step toward an enquiry.",
          author: "TRAVELA AGENCY",
          role: "Travel & Tourism",
        },
        solutionTitle: "The Solution",
        solution: "Designed and developed a modern travel agency website focused on destination discovery, tour-package presentation, travel inspiration, and customer enquiries.",
        solutionCapabilities: [
          "Modern travel-focused homepage",
          "Destination showcase",
          "Tour package sections",
          "Package detail pages",
          "Travel experiences and highlights",
          "About the agency",
          "Services section",
          "Gallery and travel imagery",
          "Customer testimonials",
          "FAQ section",
          "Contact and enquiry forms",
          "WhatsApp and direct-contact CTA",
          "Responsive mobile experience",
        ],
        solutionOutcomes: [
          "Stronger visual identity through destination-focused design",
          "Faster destination discovery for visitors",
          "Easy-to-scan tour package presentation",
          "Clear enquiry and contact actions across the journey",
          "Consistent experience across desktop, tablet, and mobile",
        ],
        technologies: [
          { name: "HTML", cat: "Structure", role: "Semantic page structure for destinations, packages, services, and enquiry content" },
          { name: "CSS", cat: "Visual Design", role: "Responsive layouts, typography, imagery, and travel-focused visual styling" },
          { name: "JavaScript", cat: "Interaction", role: "Interactive sections, navigation behavior, and visitor-facing UI actions" },
          { name: "Bootstrap", cat: "Responsive UI", role: "Responsive grid and reusable interface patterns across device sizes" },
          { name: "PHP", cat: "Contact Layer", role: "Server-side handling for enquiry and contact workflows where required" },
        ],
        engineering: [
          "A visually strong hero experience communicates the agency's travel offering with clear exploration and enquiry actions.",
          "Structured destination sections allow visitors to quickly explore available travel locations.",
          "Package cards communicate destination, duration, highlights, and enquiry options in an easy-to-scan format.",
          "Travel imagery and curated content create an emotional connection with potential travellers.",
          "Testimonials, agency information, service highlights, and FAQs help establish credibility.",
          "Contact forms and direct communication CTAs provide simple paths for interested visitors to reach the agency.",
        ],
        architecture: "Home → Destinations → Tour Packages → Package Details → Travel Experiences → About / Services → Testimonials → FAQ → Contact / Enquiry",
        result: "Delivered a modern, responsive travel website that presents the agency's destinations and offerings through an immersive visual experience while providing clear pathways for visitors to make enquiries.",
      },
      {
        key: "salon",
        name: "Salon Operations Management System",
        titlePrefix: "SALON",
        titleAccent: "OPERATIONS ERP",
        img: "assets/projects/salon/1.png",
        gallery: [
          "assets/projects/salon/1.png",
          "assets/projects/salon/2.png",
          "assets/projects/salon/3.png",
          "assets/projects/salon/4.png",
          "assets/projects/salon/5.png",
          "assets/projects/salon/6.png",
          "assets/projects/salon/7.png",
          "assets/projects/salon/8.png",
          "assets/projects/salon/9.png",
          "assets/projects/salon/10.png",
          "assets/projects/salon/11.png",
          "assets/projects/salon/12.png",
          "assets/projects/salon/13.png",
          "assets/projects/salon/14.png",
          "assets/projects/salon/15.png",
          "assets/projects/salon/16.png",
          "assets/projects/salon/17.png",
          "assets/projects/salon/18.png",
          "assets/projects/salon/19.png",
          "assets/projects/salon/20.png",
          "assets/projects/salon/21.png",
          "assets/projects/salon/22.png",
          "assets/projects/salon/23.png",
          "assets/projects/salon/24.png",
          "assets/projects/salon/25.png",
          "assets/projects/salon/26.png",
          "assets/projects/salon/27.png",
          "assets/projects/salon/28.png",
          "assets/projects/salon/29.png",
          "assets/projects/salon/30.png",
          "assets/projects/salon/31.png",
          "assets/projects/salon/32.png",
          "assets/projects/salon/33.png",
        ],
        w: 1600,
        h: 900,
        cat: "SALON TECH · OPERATIONS MANAGEMENT · 2026",
        year: "2026",
        badge: "SALON TECH · OPERATIONS MANAGEMENT · 2026",
        accent: "#b36bff",
        isLive: true,
        liveUrl: "#",
        codeUrl: "https://github.com/Anandhu1028",
        title: "Authenticated salon operations managed in one system",
        summary: "A Laravel-based salon operations management application centralizing customers, staff, services, job cards, retail sales, purchases, expenses, attendance, complaints, marketing, and reporting.",
        stats: [
          { icon: "users", value: "Role-Based", label: "Salon Operations" },
          { icon: "target", value: "Transactional", label: "Job Cards & Payments" },
          { icon: "trend", value: "Report-Ready", label: "Sales & Expenses" },
          { icon: "clock", value: "Centralized", label: "Daily Records" },
        ],
        problemTitle: "The Problem",
        problem: "Salon records were difficult to manage across disconnected manual processes. Customer and staff records, services, job cards, retail sales, purchases, expenses, attendance, complaints, marketing activity, and reports needed one authenticated system with consistent validation and operational visibility.",
        keyChallenges: [
          "Customer and staff records maintained across separate processes",
          "Service appointments represented as job cards with multiple related records",
          "Retail product sales and payments requiring structured tracking",
          "Supplier purchases and vendor payment entries needing central management",
          "Expenses, attendance, complaints, and marketing activities requiring operational records",
          "Monetary, status, relationship, and attendance rules needing validation",
          "Management reports and exports spanning multiple business modules",
        ],
        businessImpact: [
          "Reduced dependence on disconnected manual records",
          "Improved visibility across salon operations",
          "More consistent financial and status validation",
          "Centralized reporting and export workflows",
          "Clearer separation of administrator, manager, and staff access",
        ],
        testimonial: {
          quote: "A centralized salon operations application connecting customers, services, transactions, payments, staff activity, and reporting.",
          author: "SALON OPERATIONS SYSTEM",
          role: "Business Management",
        },
        solutionTitle: "The Solution",
        solution: "Implemented an authenticated salon operations management application that centralizes daily records, applies transactional business operations, and provides reporting and export workflows for management visibility.",
        solutionCapabilities: [
          "Dashboard with appointment, revenue, customer, staff, status, and performance metrics",
          "Customer and staff management with active and inactive states",
          "Service management with categories, subcategories, icons, and status control",
          "Job cards with customers, services, staff, discounts, statuses, and payments",
          "Retail cards with products, quantities, staff/customer assignment, and split or partial payments",
          "Retail products, salon-use products, tools, and equipment",
          "Purchases with vendors, line items, tax, discounts, payment status, and balances",
          "Manual purchase entries and independent vendor payment entries",
          "Expense records and expense categories",
          "Monthly staff attendance",
          "Complaint tracking linked to job cards, staff, and services",
          "Daily marketing activity tracking",
          "Sales, expense, staff, and retail-card reporting",
          "CSV, PDF, and HTML-based spreadsheet exports",
        ],
        solutionOutcomes: [
          "Automatic totals, discounts, payment states, attendance limits, and dashboard aggregates",
          "Transactional persistence for parent records and related child items",
          "Centralized customer, staff, service, purchase, expense, and complaint records",
          "Role-controlled access to operational modules",
          "Management visibility through reports, filters, pagination, and exports",
        ],
        technologies: [
          { name: "PHP 8.3 / Laravel 13", cat: "Backend", role: "Routing, middleware, controllers, validation, authentication, Eloquent, migrations, and HTTP responses" },
          { name: "Relational Database", cat: "Data Layer", role: "Eloquent relationships, foreign keys, pivot tables, payment tables, and soft deletes" },
          { name: "Blade", cat: "Frontend", role: "Server-rendered dashboards, management pages, reports, authentication screens, and reusable views" },
          { name: "Alpine.js / JavaScript", cat: "Interaction", role: "Interactive UI state, fetch-based JSON actions, status toggles, attendance, and dynamic forms" },
          { name: "Vite / Tailwind CSS", cat: "Build & Styling", role: "CSS and JavaScript entry-point builds with utility-based interface styling" },
          { name: "Chart.js", cat: "Analytics", role: "Staff performance and dashboard visualizations" },
          { name: "Dompdf", cat: "Exports", role: "PDF rendering for management list exports" },
          { name: "Custom RBAC", cat: "Security", role: "Role middleware and user-to-role access for administrator, manager, and staff" },
        ],
        engineering: [
          "Authenticated routes and custom role middleware separate administrator, manager, and staff access across operational modules.",
          "DB::transaction() protects multi-record job-card, retail-card, purchase, payment, and deletion workflows.",
          "Inline validation enforces discounts, payments, quantities, foreign keys, statuses, subcategory relationships, and attendance limits.",
          "Eloquent relationships connect users, roles, customers, job cards, services, staff assignments, payments, products, vendors, purchases, complaints, expenses, and marketing activity.",
          "Explicit states manage job cards, active and inactive master data, purchase payments, and complaint resolution workflows.",
          "Dashboard and report aggregation provides customer, staff, appointment, revenue, service, expense, retail, and performance visibility.",
          "Reusable export support produces CSV downloads, Dompdf PDFs, and HTML spreadsheet exports for management records.",
          "The current implementation does not claim inventory quantity movement, external business integrations, background jobs, public APIs, or production deployment.",
        ],
        architecture: "User → Browser → Blade / Alpine.js / JavaScript / Chart.js → Laravel Route → Authentication → Role Middleware → Controller Validation → Eloquent Models & Relationships → Relational Database → Blade / JSON / CSV / PDF Response",
        result: "Centralized salon operational data in one authenticated web application, covering customers, staff, services, transactions, payments, purchases, expenses, attendance, complaints, marketing, reporting, and exports.",
      },
      
    ],
   
  },

  

  

  /* ---- 07 · SYSTEMS & PRODUCTION ENGINEERING ---- */
  production: {
    eyebrow: "[  Production Engineering ]",
    title: "Practical Systems & Production Engineering",
    quote: "Software is not finished when it works locally. Production engineering is about keeping software reliable, observable, maintainable and efficient after deployment.",
    pipeline: [
      { step: "01", name: "CODE", desc: "Clean, modular code adhering to SOLID principles and structured naming conventions." },
      { step: "02", name: "TEST", desc: "Feature and unit verification for business rules, validation constraints, and calculations." },
      { step: "03", name: "BUILD", desc: "Asset compilation, dependency lock validation (Composer / NPM), environment configuration." },
      { step: "04", name: "DEPLOY", desc: "Git-based deployment, database migration execution, configuration caching (config:cache, route:cache)." },
      { step: "05", name: "MONITOR", desc: "Monitoring application response times, server resource utilization, and error frequencies." },
      { step: "06", name: "DEBUG", desc: "Structured log inspection, query execution plan analysis (EXPLAIN), and rapid hotfix deployment." },
      { step: "07", name: "OPTIMIZE", desc: "Database query tuning, indexing adjustments, memory footprint reduction, and code refactoring." },
    ],
    disciplines: [
      { title: "Reliability", points: ["Defensive form validation", "Database transactions (ACID)", "Graceful exception handling", "Data integrity constraints"] },
      { title: "Performance", points: ["Eliminating N+1 queries", "Indexed lookups & compound keys", "Chunked cursor pagination", "Lazy loading & asset optimization"] },
      { title: "Observability", points: ["Structured contextual logging", "Error tracking & stack trace diagnosis", "Query profiling & execution analysis", "Audit trails for business actions"] },
      { title: "Automation", points: ["Automated database migrations", "Scheduled artisan cron tasks", "Headless data processing & sync", "Chunked file imports"] },
      { title: "Security", points: ["Parameterized queries (PDO)", "CSRF token protection", "Role-based policy authorization", "Strict input sanitization"] },
      { title: "Production Operations", points: ["Git branch management", "Environment configuration (.env)", "Zero-downtime maintenance procedures", "Database backup workflows"] },
    ],
  },

  /* ---- 07b · SKILL BARS ---- */
  skillBars: {
    eyebrow: "[ Technical Skills & Mindset ]",
    title: "Skills &",
    titleAccent: "Expertise",
    note: "Honest proficiency levels based on production usage — no inflated claims.",
    groups: [
      {
        category: "Backend",
        skills: [
          { name: "Laravel", level: 90, label: "Expert" },
          { name: "PHP ", level: 88, label: "Expert" },
          { name: "Node.js ", level: 78, label: "Proficient" },
          { name: "REST API Design", level: 85, label: "Advanced" },
          { name: "MVC Architecture", level: 87, label: "Advanced" },
        ],
      },
      {
        category: "Frontend",
        skills: [
          { name: "JavaScript (ES6+)", level: 82, label: "Advanced" },
          { name: "React", level: 78, label: "Advanced" },
          { name: "HTML5 / CSS3", level: 85, label: "Advanced" },
          { name: "DOM & Browser APIs", level: 76, label: "Proficient" },
        ],
      },
      {
        category: "Database & Data",
        skills: [
          { name: "MySQL", level: 87, label: "Advanced" },
          { name: "Schema Design (3NF)", level: 82, label: "Advanced" },
          { name: "Query Optimisation", level: 78, label: "Proficient" },
          { name: "Transactions & ACID", level: 80, label: "Advanced" },
        ],
      },
      {
        category: "DSA & Systems",
        skills: [
          { name: "Algorithms & Complexity", level: 74, label: "Proficient" },
          { name: "Data Structures", level: 76, label: "Proficient" },
          { name: "System Design", level: 72, label: "Proficient" },
          { name: "Production Engineering", level: 75, label: "Proficient" },
        ],
      },
    ],
    levelMap: { Expert: 90, Advanced: 80, Proficient: 70 },
  },

  /* ---- 08 · WORK EXPERIENCE & BACKGROUND (BIG ROBOT) ---- */
  bigRobot: {
    labels: { left: "Work Experience & Education · Engineering", right: "Laravel · React · MySQL" },
    eyebrow: "[ Experience ]   ",
    titleLines: ["Engineering built for", "real business needs."],
    description: "A record of the teams, systems, and engineering responsibilities behind my work as a software developer.",
    hint: "Scroll to explore my experience.",

    techIdeas: [
      {
        no: "01",
        title: "2026 — Present · Software Developer · UGI",
        description: "Design and build enterprise-grade web applications end to end — CRM platforms, student management systems, rule evaluators, calculation strategies, and chunked Excel processing modules — using Laravel, React, and MySQL. Responsible for schema design, query optimization, and production deployment.",
        tags: ["Laravel", "React", "MySQL", "CRM / ERP", "Excel Processing", "Strategy Pattern"],
      },
      {
        no: "02",
        title: "2024 — 2025 · Full-Stack Developer · Cyenosure",
        description: "Engineered custom business applications, CRM systems, REST APIs, and administrative dashboards using Laravel, JavaScript, and MySQL for commercial clients with high-frequency operational requirements.",
        tags: ["Laravel", "JavaScript", "MySQL", "REST APIs", "Database Optimization"],
      },
      {
        no: "03",
        title: "2014 — 2018 · Networking & Cybersecurity",
        description: "National Institute of Design — studied network protocols, system security fundamentals, routing, and interface architecture, building a strong base in systems communication and defensive engineering.",
        tags: ["Network Protocols", "Systems Security", "Infrastructure"],
      },
      {
        no: "04",
        title: "2021 · Bachelor of Computer Applications",
        description: "Frontend Masters — focused on application architecture, state management patterns, and software performance fundamentals, translating algorithmic concepts into production applications.",
        tags: ["Architecture", "Data Structures", "Performance Optimization"],
      },
    ],
  },

  /* ---- 09 · TECHNICAL SKILLS & HOW I THINK (EDITORIAL) ---- */
  editorial: {
    eyebrow: "[ Technical Skills & Mindset ]",
    statement: ["Reliable systems.", "Thoughtful implementation."],
    note: "I work across the application layer, relational data layer, and production details that keep software resilient.",
    skills: {
      title: "Comprehensive Engineering Stack",
      groups: [
        { name: "Languages", items: ["PHP", "JavaScript (ES6+)", "SQL", "HTML5", "CSS3"] },
        { name: "Backend", items: ["Laravel", "REST APIs", "MVC Architecture", "Authentication (Sanctum/Session)", "Authorization (Policies/Gates)", "Artisan CLI"] },
        { name: "Frontend", items: ["React", "Vanilla JavaScript", "DOM APIs", "Responsive Design", "State Management"] },
        { name: "Database", items: ["MySQL", "Relational Database Design (3NF)", "Query Optimization", "Compound Indexing", "Transactions (ACID)", "Foreign Keys"] },
        { name: "DSA & Algorithms", items: ["Arrays & Strings", "Hash Maps & Sets", "Two Pointers", "Sliding Window", "Binary Search", "Trees & Graphs", "Time & Space Complexity"] },
        { name: "System Design", items: ["API Design", "Schema Architecture", "Database Transactions", "Queue & Background Jobs", "Data Integrity", "Security"] },
        { name: "Production & Tooling", items: ["Git", "Linux / Bash", "Composer", "NPM", "Production Debugging", "Application Logging", "Environment Config"] },
      ],
    },
    howIThink: {
      title: "How I Think: 10 Engineering Questions",
      questions: [
        { q: "What problem are we solving?", a: "Identifying the true business requirement before writing a line of code." },
        { q: "What happens with invalid input?", a: "Defensive validation at the boundary before data enters domain logic." },
        { q: "What happens when traffic increases?", a: "Analyzing query bottlenecks, table indexes, and memory footprints." },
        { q: "What happens when a dependency fails?", a: "Designing graceful degradation and structured error handling." },
        { q: "How should the database be designed?", a: "Structuring normalized schemas with strict foreign keys and transactional integrity." },
        { q: "What is the time complexity?", a: "Ensuring algorithmic efficiency and eliminating nested O(n²) loops." },
        { q: "What is the space complexity?", a: "Managing memory footprint during batch processing and query execution." },
        { q: "How will the system be monitored?", a: "Implementing meaningful contextual logging and error tracking." },
        { q: "How will the system be maintained?", a: "Writing modular code, clear migrations, and self-documenting methods." },
        { q: "How can the implementation remain simple?", a: "Choosing straightforward, maintainable solutions over speculative over-engineering." },
      ],
    },
    mindset: {
      title: "Learn → Build → Break → Improve",
      lines: [
        "I learn by building real applications.",
        "I build by understanding systems deeply.",
        "I experiment by stress-testing edge cases.",
        "And I improve by understanding why failures occur.",
      ],
    },
    exploring: {
      title: "Current Engineering Focus",
      items: [
        "High-performance relational query optimization",
        "Large-scale background data batch processing",
        "Distributed system design patterns",
        "Advanced algorithmic complexity analysis",
        "Resilient production error monitoring",
      ],
    },
    ending: {
      lines: ["Engineering software.", "Solving real problems.", "Committed to quality."],
      note: "Continuous learning and relentless improvement.",
    },
  },

  /* ---- 10 · SMALL ROBOT (STILL CURIOUS) ---- */
  smallRobot: {
    eyebrow: "[ Still Curious ]",
    titleLines: ["Always looking", "for the next challenge."],
    description: "A small machine, quietly paying attention — the way I approach every engineering problem.",
    note: "Move your cursor · it follows",
  },

  /* ---- 11 · FOOTER & CONTACT ---- */
  footer: {
    eyebrow: "[ Contact ]",
    headline: ["Let’s build", "reliable software."],
    line: "Looking for a software developer who builds production applications, understands system design, and applies algorithmic rigor? Let’s connect.",
    email: "anandhusanthosh443@gmail.com",
    emailLabel: "Send an email",
    phone: "+91 9746327402",
    focus: "Full-stack web applications, reliable APIs, system design, and production engineering.",
    skills: "Laravel · PHP · React · JavaScript · MySQL · REST APIs · DSA",
    social: [
      { label: "GitHub: Anandhu1028", href: "https://github.com/Anandhu1028" },
      { label: "LinkedIn: anandhu-a-s-b002a5232", href: "https://linkedin.com/in/anandhu-a-s-b002a5232" },
      { label: "Instagram: __a_n_a_ndhu__", href: "https://www.instagram.com/__a_n_a_ndhu__?igsi=MWxyajVwNmxsZ2JlMA==" },
    ],
    legal: "©  Anandhu. All rights reserved.",
    backToTop: "Back to top",
  },
};
